import { Account } from './types';

// This serves as the initial state for the dynamic chart of accounts.
export const INITIAL_CHART_OF_ACCOUNTS: Account[] = [
  { code: '1', name: 'ACTIVO' },
  { code: '11', name: 'ACTIVO CORRIENTE' },
  { code: '1101', name: 'CAJA' },
  { code: '1102', name: 'BANCOS' },
  { code: '1103', name: 'IVA crédito fiscal' },
  { code: '1104', name: 'Clientes' },
  { code: '2', name: 'PASIVO' },
  { code: '21', name: 'PASIVO CORRIENTE' },
  { code: '2101', name: 'CUENTAS POR PAGAR' },
  { code: '2101.01', name: 'Acreedores diversos' },
  { code: '2101.02', name: 'Documentos por pagar' },
  { code: '2101.03', name: 'Anticipos de clientes' },
  { code: '2102', name: 'OBLIGACIONES LABORALES' },
  { code: '2102.01', name: 'Sueldos por pagar' },
  { code: '2103.02', name: 'Retenciones de renta por pagar' },
  { code: '2103', name: 'OBLIGACIONES FISCALES' },
  { code: '2103.01', name: 'IVA débito fiscal' },
  { code: '2103.02', name: 'Retenciones de IVA por pagar' },
  { code: '2103.03', name: 'Pago a cuenta por pagar' },
  { code: '22', name: 'PASIVO NO CORRIENTE' },
  { code: '2201', name: 'Documentos a pagar a largo plazo' },
  { code: '3', name: 'PATRIMONIO' },
  { code: '31', name: 'PATRIMONIO' },
  { code: '3101', name: 'Capital social' },
  { code: '3102', name: 'Reserva legal' },
  { code: '3103', name: 'Utilidades retenidas' },
  { code: '3104', name: 'Pérdidas acumuladas' },
  { code: '3105', name: 'Utilidades del ejercicio' },
  { code: '3106', name: 'Pérdidas del ejercicio' },
  { code: '4', name: 'INGRESOS' },
  { code: '41', name: 'INGRESOS OPERACIONALES' },
  { code: '4101', name: 'Desarrollo de software' },
  { code: '4102', name: 'Mantenimiento de software' },
  { code: '4103', name: 'Capacitación' },
  { code: '4104', name: 'Consultoría técnica' },
  { code: '42', name: 'OTROS INGRESOS' },
  { code: '4201', name: 'OTROS INGRESOS' },
  { code: '5', name: 'GASTOS' },
  { code: '51', name: 'GASTOS DE PERSONAL' },
  { code: '5101', name: 'Sueldo de desarrolladores' },
  { code: '52', name: 'GASTOS TECNOLÓGICOS' },
  { code: '5201', name: 'Servicios de hosting y servidores' },
  { code: '5202', name: 'Dominios Web' },
  { code: '5203', name: 'Servicios en la nube' },
  { code: '5204', name: 'Mantenimiento de equipo de cómputo' },
  { code: '5205', name: 'Internet' },
  { code: '53', name: 'GASTOS ADMINISTRATIVOS Y OPERATIVOS' },
  { code: '5301', name: 'Agua' },
  { code: '5302', name: 'Teléfono' },
  { code: '5303', name: 'Artículos de limpieza' },
  { code: '5304', name: 'Energía eléctrica' },
  { code: '54', name: 'Gastos de Depreciación' },
  { code: '5401', name: 'Depreciación de equipo de cómputo' },
  { code: '5402', name: 'Depreciación de equipo de mobiliario' },
  { code: '55', name: 'Gastos de Ventas y Marketing' },
  { code: '5501', name: 'Publicidad y propaganda' },
  { code: '5502', name: 'Marketing digital' },
  { code: '56', name: 'Gastos Varios' },
  { code: '5601', name: 'Cuentas incobrables' },
  { code: '5602', name: 'Otros gastos no operacionales' },
  { code: '6', name: 'CUENTA DE CIERRE' },
  { code: '61', name: 'CUENTA DE CIERRE' },
  { code: '6101', name: 'Pérdidas y ganancias' },
];

export const IVA_RATE = 0.13; // 16%